# Generated by Django 4.0.3 on 2022-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvo',
            name='name',
        ),
        migrations.AddField(
            model_name='locationvo',
            name='closet_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locationvo',
            name='section_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationvo',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
